sudo: false
language: ruby

rvm:
  - "2.5.3"
  - "2.4.5"
  - "2.3.8"
  - "jruby-9.2.0.0"

script: make default

matrix:
  allow_failures:
  - rvm: jruby-9.2.0.0
jobs:
  include:
  - stage: deploy
    ruby: "2.5.3"
deploy:
  skip_cleanup: true
  provider: rubygems
  api_key:
    secure: WhgpNQtu2vXx4h9v9MNHwqiEfKui1TiH1tTGXzpJe54eK0wiJFlH+xqRRDcD/IMLnHuma0bZkqxX7/dO9XeehBGcLA+74mMDCV4iOfJXzzuqcMDXYwi9hNEYjrT+kU0h3Sj455dJvwTGU748QcfBKWxV9qUvYmtrTKNI3La7j57mOIcaiqtKcCOfMPvYO9QOZem/1R8XZD9CmuDv+fpq9xcDkPSElEQIHhZRDH+ylamVrGAdUriOvInpIG/QLq2c+VrAzFXeUgDz5LX4aENlb5Hsv7VdXzLzYgjRLRE0dBxB9MsYDCxfI9rVzK/0OrfWOeJNY0yCSL+zoTcWGpkgPyqaMgDXZ5EYp0/MKKzZWdwBUQnc8R5rXT11YfpAKSCE7c1cPyw/K55PuEYZv9WjrpY5MsYbuQFeogWHdjmZ+hSw4SddceUcWG7BpP7Y0zOfIwNx756SqMWOtsK68fiEOKmoUaDhb1yR5gBxWirsw0rTl5leJVBCP/1hERB337pp0Ix+A7oUS2nDeZUBNdZ0TUxEaN3PZprKGs/BBUS203ibhBfnQMdDNBBBNe4rLcIge2wdVw65P2bTLs0wrdaFCRdjg4xtSwimOl0LIF0PNMLoeyuhq+Yd306PDYtt4FNgbIaLUOaG+6gRM3k2mIEQ106xqUmaQqiCju72L95P24I=
  gem: c21e
  on:
    tags: true
